### ISSUE TITLE
Allow downloading single RFC documents

### ISSUE THREAD

**Issue by joshfriend** [monsieurh/rfc_reader#2]
The whole archive of RFC documents is currently 167MB. It would be cool if downloading the whole archive on first run was optional (but still possible for offline reference), and instead only download the documents as the user requests them. This would also mean you wouldn't have to run a full update to read new RFCs.

**Comment by monsieurh** [comment]
I'm unconfortable about it. The main focus is to have offline access. As someone pointed out on reddit, `surfraw` already does a good job at downloading/caching RFCs on demand.
