### ISSUE TITLE
Case-insensitive keyword

### ISSUE THREAD

**Issue by FrankSansC** [monsieurh/rfc_reader#3]
It would be great to ignore the case when looking for a keyword. Right now looking for "Relay" returns several results but looking for "relay" returns none.

**Comment by monsieurh** [comment]
You're right. I will make it the default, as adding a new flag would just cripple the readability.

**Comment by monsieurh** [comment]
Fixed by `b3bb90013aca89f953c00a4627472efcd554ef03`
