### ISSUE TITLE
Support RFC downloaded from distro package manager

### ISSUE THREAD

**Issue by MartijnBraam** [monsieurh/rfc_reader#7]
Arch linux has a rfc package which puts files in `/usr/share/doc/rfc/txt/{num}.txt` and the index in `/usr/share/doc/rfc/rfc-index.txt`. These might be used if the local RFC dir doesn't exist yet.

For debian/ubuntu/etc the `doc-rfc` package puts the docs in `/usr/share/doc/RFC/{section}/{num}.txt.gz` so that is slightly harder to implement since the index is split over several files.

**Comment by monsieurh** [comment]
The objective is to be independent from different distro/architectures, so I won't spend time on that issue.
